# this workflow to activate on each push to repository
name: WorkFlow for test before push
on: [push]
jobs:
    Run-checks:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
            # this step use the oficial action to clone the repository
              uses: actions/checkout@v4
            - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

            # set up the environment of python
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.x'
            
            # installing all dependeces of the project write on requeriments.txt
            - name: Install dependencies
              run: |
               python -m pip install --upgrade pip
               pip install -r requirements.txt

            # run all test of the project using pytest
            - name: Run tests
              run: |
               pytest
